### PR TITLE
Modernization

### LINKED ISSUE #3: Use async keyword instead of asyncio.coroutine
Python 3.5 introduced the `async` and `await` syntax to work with async functions. The `@asyncio.coroutine` decorator has been deprecated as of Python 3.8 and prints a warning when it's used ([example](https://github.com/home-assistant/core/runs/1342394326?check_suite_focus=true#step:8:355)). It is going to be removed in Python 3.10.

Rewriting it is straight forward:

```python
# before
@asyncio.coroutine
def my_func():
    yield from other_func()

# new
async def my_func():
    await other_func()
```

To be future proof for future Home Assistant versions, it would be good to migrate to `async` and `await` syntax.

### LINKED ISSUE #5: Can't initialize connection through HomeAssistant
Looks like underlying dependency modified the signature of the method that is used for async connection. Here's a stack trace:

```
Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/monoprice/config_flow.py", line 80, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/usr/src/homeassistant/homeassistant/components/monoprice/config_flow.py", line 59, in validate_input
    await get_async_monoprice(data[CONF_PORT], hass.loop)
  File "/usr/local/lib/python3.10/site-packages/pymonoprice/__init__.py", line 381, in get_async_monoprice
    _, protocol = yield from create_serial_connection(loop, functools.partial(MonopriceProtocol, loop),
  File "/usr/local/lib/python3.10/site-packages/serial_asyncio/__init__.py", line 449, in create_serial_connection
    transport, protocol = await connection_for_serial(loop, protocol_factory, serial_instance)
  File "/usr/local/lib/python3.10/site-packages/serial_asyncio/__init__.py", line 476, in connection_for_serial
    protocol = protocol_factory()
  File "/usr/local/lib/python3.10/site-packages/pymonoprice/__init__.py", line 350, in __init__
    self._connected = asyncio.Event(loop=loop)
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 168, in __init__
    super().__init__(loop=loop)
  File "/usr/local/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Event() since it is no longer necessary
```

### PR DESCRIPTION
**Pull request by flacjacket**
This is a large modernization and update of the pymonoprice package. This includes updating the library to use the most recent asyncio APIs, adding additional python 3.10-style type annotations, and use dataclasses for the zone status. This also includes the changes in #6. Other improvements include adding a `py.typed` file to communicate that the library includes type annotations, moving the internally scoped classes to global scope to use externally for typing, fixing up existing type annotations, and updating the formatting using `black`.

Closes #3
Closes #5

### CODE REVIEW

**Review by etsinko — CHANGES_REQUESTED** [review]
This commit breaks tests.

**Comment by flacjacket** [comment]
No problem! Squashed those commit together, also added a github actions config to run tests on the PR itself.

**Review by etsinko — APPROVED** [review]

**Comment by etsinko** [comment]
I got a question about this `all_zone_status()` method. I don't think I can verify it on my monoprice as it is too old. What is it supposed to do?
I see the request is identical to `zone_status()` but in the response 168 bytes are expected. If it returns all zones then why does it require a parameter `zone`? Can you send me a sample request - response pair so I can mock a test case?

**Comment by flacjacket** [comment]
The all zone status lets you query all of the zones on a given controller. If you query zones 10, it returns all of the zone statuses for zones 11-16, similarly for requesting zone 20 or 30 to query 21-26 or 31-36. Here is what I get as an example:
```
>>> mp.all_zone_status(10)
DEBUG:pymonoprice:Sending "b'?10\r'"
DEBUG:pymonoprice:Received "b'?10\r\n#>1100000000130707100600\r\r\n#>1200000000150707100600\r\r\n#>1300000000110707100600\r\r\n#>1400000000140707100600\r\r\n#>1500000000200707100100\r\r\n#>1600000000200707100100\r\r\n#'"
[ZoneStatus(zone=11, pa=False, power=False, mute=False, do_not_disturb=False, volume=13, treble=7, bass=7, balance=10, source=6, keypad=False), ZoneStatus(zone=12, pa=False, power=False, mute=False, do_not_disturb=False, volume=15, treble=7, bass=7, balance=10, source=6, keypad=False), ZoneStatus(zone=13, pa=False, power=False, mute=False, do_not_disturb=False, volume=11, treble=7, bass=7, balance=10, source=6, keypad=False), ZoneStatus(zone=14, pa=False, power=False, mute=False, do_not_disturb=False, volume=14, treble=7, bass=7, balance=10, source=6, keypad=False), ZoneStatus(zone=15, pa=False, power=False, mute=False, do_not_disturb=False, volume=20, treble=7, bass=7, balance=10, source=1, keypad=False), ZoneStatus(zone=16, pa=False, power=False, mute=False, do_not_disturb=False, volume=20, treble=7, bass=7, balance=10, source=1, keypad=False)]
```
The format of the query is the same as for an individual zone, but just with 10, 20, or 30 for the zone. Because each zone has a separate `\r\r\n` EOL sequence, we can't break based on that, so I figured to just read in a constant size. Looking at it now, we could use the current read with a `skip=141` to skip over the return values of the first 5 zones.

**Comment by etsinko** [comment]
Thanks! I'll add a unit test and tinker with it. I see that because of this special case we have two pairs of almost identical methods: `send()` / `send_sized()` and `_process_request()` / `_process_request_sized()`
I'll merge them.

**Comment by etsinko** [comment]
Actually I think it is easier to remove `skip` parameter and instead use `number_of_lines` parameter which will ensure that we are reading exactly the required number of EOLs

**Comment by etsinko** [comment]
What is the use case to query all zones at the same time? Currently homeassitant plugin only queries them one by one

**Comment by etsinko** [comment]
Just merged it. Thank you for your help! 
I also changed the functionality slightly, do you mind testing it if possible? The only difference is that `all_zone_status()` takes `unit` parameter instead of `zone`. `unit` must be between 1 and 3 inclusive

**Comment by etsinko** [comment]
If everything looks good, I can create a release tomorrow

**Comment by flacjacket** [comment]
I like the idea to use the EOL count to read everything in a unified way!

The new function with the single digit `unit` works great, thanks for updating that!

**Comment by OnFreund** [comment]
@flacjacket what's the return value when there's no relevant unit? (e.g. unit 3 when you only have 2?

**Comment by flacjacket** [comment]
In that case, it behaves the same as requesting the zone status of a unit
you don't have, like for zone status 31 in that case with 2 units. In
particular, the controller just echos the input command but doesn't return
any data, so we will just raise a serial exception on timeout.

**Pull request merged**
